
name: CD

on:
  push:
    branches:
      - new-arch
      - dev

  workflow_dispatch:

env:
  BRANCH_NAME: ${GITHUB_REF##*/}

jobs:
  DeployToAWS:
    runs-on: ubuntu-latest
    environment:
        name: dev
    permissions:
      id-token: write
      contents: read

    steps:
        - uses: actions/checkout@v2

        - name: Setup AWS Credentials
          run:
            echo "BRANCH_NAME: $BRANCH_NAME"

          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-region: ${{ secrets.AWS_REGION }}
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
            role-session-name: github-action

#        - name: Installing Dependencies
#          run: |
#            npm install -g aws-cdk
#            cd iac
#            pip install -r requirements.txt
#
#
#        - name: DeployWithCDK
#          run: |
#            cd iac
#            cdk synth
#            cdk deploy --require-approval never
